### ISSUE TITLE
Resolvable Items are not always children of StartItem

### ISSUE THREAD

**Issue by slevkelevra** [ParTech/Seo-Friendly-Url#6]
Hi Ruud,

first of all, thank you for the great module. I've discovered a problem with the use of your module.
In your resolver you go on the assumption that all resolvable Items must be below the StartItem.
This is also reflected in your ItemResolver code.

The HttpRequestArgs args.Url.ItemPath property is by default composed of RootPath + StartItem + LocalPath.
The method ResolveItem is thus always called with StartItem in the path parameter.

The Problem is that in my current project all resolvable items are siblings of StartItem and not children.

To make your ItemResolver more generic, it requires a handling which calls the method ResolveItem with different or customized parameter values, when variable resolved equals null.

Btw, In Sitecore.Pipelines.HttpRequest.ItemResolver the handling of various ItemsPath is also implemented.

Right now I have the problem solved as follows: (ItemResolver.cs:107)

<pre>

// Resolve the item with security disabled.
// Security will be applied after an item has been resolved.
using (new SecurityDisabler())
{
  resolved = ResolveItem(args.Url.ItemPath) ?? ResolveItem(Context.Site.RootPath + args.LocalPath);
}

</pre>
You know what I mean? Maybe you can implement the better.

Many greetings
Maik

**Comment by DotTech** [comment]
Hi Maik,

Sorry for taking ages to reply, but I wanted you to know that your
suggestion has been applied to version 1.0.15 of the module.
Thank you for your contribution!

Best regards,
Ruud van Falier

On Wed, Dec 17, 2014 at 1:48 PM, Slev Kalevra <notifications@github.com>
wrote:

> Hi Ruud,
>
> first of all, thank you for the great module. I've discovered a problem
> with the use of your module.
> In your resolver you go on the assumption that all resolvable Items must
> be below the StartItem.
> This is also reflected in your ItemResolver code.
>
> The HttpRequestArgs args.Url.ItemPath property is by default composed of
> RootPath + StartItem + LocalPath.
> The method ResolveItem is thus always called with StartItem in the path
> parameter.
>
> The Problem is that in my current project all resolvable items are
> siblings of StartItem and not children.
>
> To make your ItemResolver more generic, it requires a handling which calls
> the method ResolveItem with different or customized parameter values, when
> variable resolved equals null.
>
> Btw, In Sitecore.Pipelines.HttpRequest.ItemResolver the handling of
> various ItemsPath is also implemented.
>
> Right now I have the problem solved as follows: (ItemResolver.cs:107)
>
>
> // Resolve the item with security disabled.
> // Security will be applied after an item has been resolved.
> using (new SecurityDisabler())
> {
>   resolved = ResolveItem(args.Url.ItemPath) ?? ResolveItem(Context.Site.RootPath + args.LocalPath);
> }
>
>
> You know what I mean? Maybe you can implement the better.
>
> Many greetings
> Maik
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParTech/Seo-Friendly-Url/issues/6>.
>



-- 
Met vriendelijke groet,

Ruud van Falier
*DotTech*
*___________________________*
Mobiel: +316 51 44 73 63
E-Mail: ruud@dottech.nl
Web: http://www.dottech.nl
LinkedIn: http://nl.linkedin.com/in/ruudvanfalier
