### ISSUE TITLE
infinite redirect loop scenario

### ISSUE THREAD

**Issue by XpressiveCode** [ParTech/Seo-Friendly-Url#7]
1. set languageEmbedding="always"
2. go to your site and try to access content outside of your site 

An example might be:
`http://demosite/sitecore/content/home` (assuming you still have the home node from the base install)

This will cause the module to constantly loop between

`http://demosite/en/sitecore/content/home?sc_lang=en `
and
`http://demosite/sitecore/content/home?sc_lang=en`

It just keeps swapping between the two until the browser throws up

**Comment by XpressiveCode** [comment]
I'm not sure if there is anything that you can do about this. It doesn't look like the language is passed through to your ForceFriendlyUrl method. So the check to see if requestedPath matches the friendlyPath will never macth. The language url segment is missing. Instead, sitecore (in the scenario described in the issue) replaces the /en with sc_lang=en, which causes your link provider to try again and the whole cycle starts over again.

For now, I've added an additional check in the IgnoreRequest method. 

```cs
HttpContext.Current.Request.Url.AbsolutePath.StartsWith("/sitecore/content", StringComparison.InvariantCultureIgnoreCase)
|| ...
```

I don't know how many people link to content outside of their site (global assets perhaps), but this works. 

If you think it's something worth having, I can send you a PR.

**Comment by DotTech** [comment]
Hi Mike,

Thanks for your report!
I've updated the module to ignore resolving if the request URL starts with
/sitecore/content.
It seems like a good solution for now.

Best regards,
Ruud

On Thu, Apr 30, 2015 at 9:40 PM, Mike Fitzgerald <notifications@github.com>
wrote:

> I'm not sure if there is anything that you can do about this. It doesn't
> look like the language is passed through to your ForceFriendlyUrl method.
> So the check to see if requestedPath matches the friendlyPath will never
> macth. The language url segment is missing. Instead, sitecore (in the
> scenario described in the issue) replaces the /en with sc_lang=en, which
> causes your link provider to try again and the whole cycle starts over
> again.
>
> For now, I've added an additional check in the IgnoreRequest method.
>
> HttpContext.Current.Request.Url.AbsolutePath.StartsWith("/sitecore/content", StringComparison.InvariantCultureIgnoreCase)
> || ...
>
> I don't know how many people link to content outside of their site (global
> assets perhaps), but this works.
>
> If you think it's something worth having, I can send you a PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParTech/Seo-Friendly-Url/issues/7#issuecomment-97941374>
> .
>



-- 
Met vriendelijke groet,

Ruud van Falier
*DotTech*
*___________________________*
Mobiel: +316 51 44 73 63
E-Mail: ruud@dottech.nl
Web: http://www.dottech.nl
LinkedIn: http://nl.linkedin.com/in/ruudvanfalier
